seed: 42
do_train: True 
do_predict: True

# top-level config #
paradigm: seq2seq
task_name: EAE
dataset_name: ACE2005-dygie
language: English
test_exists_labels: True

# file path #
output_dir: /kaggle/tmp/OmniEvent/output/DuEE1.0
type2id_path: /kaggle/input/chinese-duee/label2id.json
role2id_path: /kaggle/input/chinese-duee/role2id.json
train_file: /kaggle/input/chinese-duee/train.unified.jsonl
validation_file: /kaggle/input/chinese-duee/valid.unified.jsonl
test_file: /kaggle/input/chinese-duee/test.unified.jsonl

# event detection predictions
golden_trigger: True
train_pred_file: /kaggle/tmp/OmniEvent/output/DuEE1.0/ED/token_classification/bert-base-uncased-marker/train_preds.json
validation_pred_file: /kaggle/tmp/OmniEvent/output/DuEE1.0/ED/token_classification/bert-base-uncased-marker/valid_preds.json
test_pred_file: /kaggle/tmp/OmniEvent/output/DuEE1.0/ED/token_classification/bert-base-uncased-marker/test_preds.json

# config for data processor # 
truncate_in_batch: True 
return_token_type_ids: False 
truncate_seq2seq_output: True

# model config #
model_type: t5
model_name_or_path: t5-base
backbone_checkpoint_path: t5-base
hidden_size: 768
aggregation: none

# training config #
num_train_epochs: 1
max_seq_length: 160
max_out_length: 128
dataloader_num_workers: 2
early_stopping_patience: 100

generation_max_length: 128
generation_num_beams: 4
predict_with_generate: True 
ignore_pad_token_for_loss: True 

per_device_train_batch_size: 4
per_device_eval_batch_size: 8
gradient_accumulation_steps: 2
# eval_accumulation_steps: 4
learning_rate: 1.0e-4
weight_decay: 1.0e-5
warmup_ratio: 0.1 
max_grad_norm: 1.0
optim: adamw_torch
# lr_scheduler_type: constant

logging_strategy: steps
logging_steps: 100

evaluation_strategy: epoch      # Evaluate at the end of each epoch
save_strategy: epoch            # Save checkpoint at the end of each epoch
save_total_limit: 2             # Only keep the best and the last checkpoint
load_best_model_at_end: True    # Load the best model at the end of training   
metric_for_best_model: micro_f1 # Metric for choosing the best model
greater_is_better: True  

# split inference #
split_infer: False
split_infer_size: 5000

